name: Next.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    outputs:
      build_start_time: ${{ steps.record_build_start_time.outputs.build_start_time }}

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Включение Yarn через Corepack
        run: corepack enable yarn

      - name: Установка зависимостей
        run: yarn install --frozen-lockfile

      - name: Запуск тестов
        run: yarn test

      - name: Запись времени начала сборки
        id: record_build_start_time
        run: echo "build_start_time=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Сохранение коммит-сообщения и имени пользователя
        run: |
          echo "GITHUB_COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
          echo "GITHUB_ACTOR=${{ github.actor }}" >> $GITHUB_ENV
          echo "Коммит: ${{ github.event.head_commit.message }}"
          echo "Пользователь: ${{ github.actor }}"


      - name: Оповещение в Telegram — старт сборки
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "parse_mode=Markdown" \
            --data-urlencode "text=\`\`\`
            🚀 Сборка началась
            Пользователь: $GITHUB_ACTOR
            Проект: ${{ secrets.PROJECT_NAME }}
            Ссылка: ${{ secrets.PROJECT_LINK }}
            Коммит: $GITHUB_COMMIT_MESSAGE
            \`\`\`"

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Создание .env файла из GitHub Secrets
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env.production
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.production
          echo "API_URL=${{ secrets.API_URL }}" >> .env.production
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env.production
          echo "NEXT_PUBLIC_VAPID_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_VAPID_PUBLIC_KEY }}" >> .env.production
          echo "NEXT_PUBLIC_COMPANY_ID=${{ secrets.NEXT_PUBLIC_COMPANY_ID }}" >> .env.production
          echo "NEXT_PUBLIC_CHAT_REST_URL=${{ secrets.NEXT_PUBLIC_CHAT_REST_URL }}" >> .env.production
          echo "NEXT_PUBLIC_CHAT_WEBSOCKET_URL=${{ secrets.NEXT_PUBLIC_CHAT_WEBSOCKET_URL }}" >> .env.production
          echo "NEXT_PUBLIC_OPENAI_API_KEY=${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }}" >> .env.production

      - name: Проверка и создание сети Docker (если отсутствует)
        run: |
          docker network inspect nextjs_network >/dev/null 2>&1 || docker network create nextjs_network

      - name: Сборка нового Docker-образа
        run: docker compose -f docker/production/compose.yaml build --no-cache

      - name: Остановка старого контейнера (если существует)
        run: |
          if docker ps -q --filter "name=app-mamanfest-frontend" | grep -q .; then
            echo "Останавливаем старый контейнер..."
            docker stop app-mamanfest-frontend || true
            docker rm app-mamanfest-frontend || true
          else
            echo "Старый контейнер не найден."
          fi

      - name: Запуск нового контейнера
        run: docker compose -f docker/production/compose.yaml up -d --no-deps

      - name: Проверка работоспособности контейнера
        run: |
          for i in {1..10}; do
            if curl -f http://127.0.0.1:3001; then
              echo "Контейнер работает корректно."
              break
            fi
            echo "Ожидание запуска контейнера..."
            sleep 5
          done

      - name: Вычисление времени сборки и деплоя
        if: always()
        id: compute_time
        run: |
          END_TIME=$(date +%s)
          START_TIME=${{ needs.build.outputs.build_start_time }}
          DURATION=$(( END_TIME - START_TIME ))
          echo "build_time=$DURATION" >> $GITHUB_OUTPUT

      - name: Сохранение коммит-сообщения и имени пользователя
        run: |
          echo "GITHUB_COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
          echo "GITHUB_ACTOR=${{ github.actor }}" >> $GITHUB_ENV
          echo "Коммит: ${{ github.event.head_commit.message }}"
          echo "Пользователь: ${{ github.actor }}"

      - name: Оповещение в Telegram — успешный деплой
        if: success()
        run: |
          build_time=${{ steps.compute_time.outputs.build_time }}
          source $GITHUB_ENV
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "parse_mode=Markdown" \
            --data-urlencode "text=\`\`\`
            ✅ Деплой успешный
            Пользователь: $GITHUB_ACTOR
            Проект: ${{ secrets.PROJECT_NAME }}
            Коммит: $GITHUB_COMMIT_MESSAGE
            Время сборки+деплоя: ${build_time} c
            \`\`\`"

      - name: Оповещение в Telegram — ошибка деплоя
        if: failure()
        run: |
          build_time=${{ steps.compute_time.outputs.build_time }}
          source $GITHUB_ENV
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "parse_mode=Markdown" \
            --data-urlencode "text=\`\`\`
            ❌ Деплой не удался
            Пользователь: $GITHUB_ACTOR
            Проект: ${{ secrets.PROJECT_NAME }}
            Коммит: $GITHUB_COMMIT_MESSAGE
            Время сборки+деплоя: ${build_time} c
            \`\`\`"

  cleanup:
    runs-on: self-hosted
    if: always()
    needs: [build, deploy]
    steps:
      - name: Удалить неиспользуемые ресурсы Docker
        run: |
          docker image prune -af
          docker container prune -f
          docker network prune -f
          docker builder prune -af
